Change the condition for wrapping the root in an array
This should result in a message from the path.resolve method:
`TypeError: Path must be a string.`
Instead of `.map is not a function`