Fix: use the cwd option for glob patterns (#157)
* Use the cwd option for the glob patterns

* Misc

* Change the condition for wrapping the root in an array

This should result in a message from the path.resolve method:
`TypeError: Path must be a string.`
Instead of `.map is not a function`